### ISSUE TITLE
Preferred way of installation?

### ISSUE THREAD

**Issue by mairas** [Reactduino/Reactduino#2]
Hi,

Have been playing with Reactduino a bit and so far I quite like it. I've got just one question: what is the preferred way to install the library? If I just try to install it with Arduino IDE (or even by copying it to place), my sketches won't find the includes because they're under `src`. If I copy the source files up to the root folder, Arduino IDE is able to build the project.

**Comment by AndrewCarterUK** [comment]
I use PlatformIO myself, so I'm not sure on the best approach for the Arduino IDE.

It looks like you can install a ZIP library, which should work with this download link: [https://github.com/Reactduino/Reactduino/archive/master.zip](https://github.com/Reactduino/Reactduino/archive/master.zip) which you can get from the main repository.

Can you let me know if that works for you?

**Comment by mairas** [comment]
That's the way I've done it, but the Arduino IDE doesn't seem to find the headers under the `src` directory.

Hmm, it seems the Arduino IDE would expect a `library.properties` file which could then define the header files. I can experiment with it and make a PR if that'd fix it.

**Comment by AndrewCarterUK** [comment]
That would be very much appreciated!

**Comment by AndrewCarterUK** [comment]
Closed by #4
